language: bash
sudo: required
env:
  global:
    - secure: "Lhh3KEmMJhRI74J738AR1Bve1qiLx4aQhcosbbnJWOoioGtLV6t/BvihubcfDKKrtr5E8nHQh3GvHsqRbYZ9y7ISHzW3ns9CcUi1zVCgprdknSwErITRm2BQ1VQhrKFw2GeZll7/vnB8HKfK0htWBMh21g3i9QzsnGPaspx14fhZUjIYKWCYgaiT3qh6F3n4PHt8u5lEgEQsH+HEthPX2n7qu/zgUotk+kk3EIbqznToamQoZ9jsOA0Km51smART6VE00VzqggPfYzYu+KxUHPJtqBOedShkYXGvThQbf9hTmg9OpT0bSCISaS2hMgvoVoWjXVQVbf3LlMB9t5kZajY6hC6th+JvUL5auhn0cv7A0tjf2NWD74TFqP5IO2GPTFHsnbR4jUEIqCsEms+TkAJX4bLGGBZ7S9vz3RasP9o7Gkf+D5uPiGMTiInhHx2JvT2ZP2NwOeWmJ1ACneHTV/vUtkAlpMRsVuOgrXHd8+V+WAY0WSR+t+qXuyZDP3KHoK8aqI5kiD0nsX6M+/Mec/rFP2BjOBCngocE6/J+VZDi3rBZXgNmt66nXqtZsa3f1UthEJVJEhNDTJ0/6jXv6dbLk37uiw++Q8EzFZl9KK2hWCaOnYRuGLrbefg8onZkBUhBBSf8gfpuEy4/v2icFOMvRiOFYs5q+IqOMsiA5j4="
    - secure: "dTlCP3+O+DV6ioQQysAtPXYLRDN5nDtSK27dwEODRMwzqn7yH/w+JpIPhbdg8Nbe1CnMoiyqkmrVCzUsgZD9HXuPDArJJcE5C568wXnu5QZyhaTq5bRiKiJw8YpC4AtpQ03qXPPc/Z+w0aOceWrriihwKWNtZuhY8Y+TYjdlX5irsPttyxUPlI3j4upw8CH4J0PChZ3UL0SVA67u9hPlK8uyEmm6X3I8I2WfPCmHB0j3YRFkm/imWwjbT+rm/GlaBocD8iXhgy/uCX+tAB/sLFpTW7vwumwIAPk1LFARhuHTGg2mvufOO/PGGMSKvagPTlMoribxBtAbCypf9c7Epzd7KIB803sgnIZsWNkd6o5zKz27fuOOlEdm7SnvQBLFaCkFY76fvT9lpVpWX6djLBOut15JTWFxDmGzTVc5z6gB/dmLEH9oWNEPTBvB5Cl0h7fXuHOOfVCng0Ax2lo0cywDTDRcN8JiX1aoCAw1Bp3ujsUwITd9Jh5w9haX3rA4RDurynrPeZAmIxH3ilOk8PF8E8bQjssJ98bNtY+q1piNXuIZjRhHb/ypSu2ZD/kxJqkF7ha6JnfeBYzhIKOpPPENXFlpmVZUVIhLN288pwpaF7cFvNPiOH3JKzo6BAjnB4WD0i+W+IauYtvvhlexule5Cawbzx3kpOzrS8ccN3o="
    - secure: "AfvZJhuQISeiN7u6mrmmOE1VVYjgQdLeT5HNZLigrKrONKvyo3xs3LnaEWt0SkucTiGy6l3iLHZKbyQvreguJySfkxnzeA/RvP41bPY1yvtc/Z5nAoyUd1nmnSGAeb9YflB9cc3oyiWNgZEPbl3rL2o1pJogpZRuWdkF3Msl4xh6MzgfrG47fRaPZCF+xuANZ2BneExKNdt1Bu7kZDoDxPzqdlrwi0wIGrwZtyNOSI83pBain7dQzDFAVvGONqKKoe5pRa1pHi3Q3BX8QVr6bYOBezXv/4hyoJuKGwsfPLoxgxtEZCsFccbIbVUEsG2tlgVGmIJxqjxiYDKME4H4aCSMnoPJub/EQhuOE7/xk+3rRW5HN94UcAAdGDAGC3wEv8wTKJDfTR3PwIhbOddxKw5Tz+C+oDxzlNRUl7BB5OkJ4G9uYIoMPrsgUS7eakz/sYvc9zePkUmjYwICO+225a4CB/CJ1coZt7ZdjbI08zGC/YIvMvrq/saD+jnwNTdyIuijnM2fdlc79LwuZ46tsVE8euIzRelNWzaWvSqgQC5M65RKDN1QlkGOYiBOHMi4oZFWYH34HJGzgN8KNUOyfG8NYLm3V/geal5SVyVlaeju7K8AevkKN5EwXBtBJEaAau40AOnWMaOvPGtqMjprLtTmtmUj5hCv9SWXAMjrX/c="
    - K8S_OPS_REPO_BRANCH=master
    - K8S_OPS_REPO_SLUG=OriHoch/knesset-data-k8s
    - DOCKER_IMAGE=orihoch/knesset-data-pipelines
    - DEPLOY_YAML_UPDATE_FILE=environments/production/values.auto-updated.yaml
    - DEPLOY_VALUES_CHART_NAME=pipelines
    - DEPLOY_VALUES_IMAGE_PROP=image
    - DEPLOY_COMMIT_MESSAGE="automatic update of knesset-data-pipelines"
    - DEPLOY_GIT_EMAIL=knesset-data-deployer@null.void
    - DEPLOY_GIT_USER=knesset-data-deployer
services:
  - docker
script:
  - curl -s https://raw.githubusercontent.com/hasadna/hasadna-k8s/master/apps_travis_script.sh > .travis.sh
  - bash .travis.sh script
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
    condition: `echo "${TRAVIS_COMMIT_MESSAGE}" | grep -q -- --no-deploy && echo 1` != "1"
